object Versions {
    const val kotlin = "1.9.0"
    const val agp = "8.1.2"
    const val daggerHilt = "2.48"
    const val coreKtx = "1.9.0"
    const val roomVersion = "2.5.2"
    const val navVersion = "2.6.0"
    const val retrofitVersion = "2.9.0"
    const val gsonVersion = "2.10.1"
    const val lifecycleKtx = "2.6.2"
    const val appCompatVersion = "1.6.1"
    const val materialVersion = "1.8.0"
    const val constraintLayoutVersion = "2.1.4"
    const val fragmentKtx = "1.6.2"
    const val junitVersion = "4.13.2"
    const val extJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val coroutines = "1.7.1"
    const val logging = "4.11.0"
}